name: Test PR wf

on:
  pull_request:

jobs:
  deploy_job:
    name: deploy to curr branch
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."